[package]
name = "check-if-email-exists-cli"
version = "0.8.15"
default-run = "check_if_email_exists"
edition = "2018"
license = "AGPL-3.0"
publish = false

[[bin]]
name = "check_if_email_exists"
path = "src/main.rs"

[dependencies]
check-if-email-exists = { path = "./core" }
clap = { version = "2.33", features = ["yaml"] }
env_logger = "0.8"
hyper = { version = "0.13" }
serde = "1.0"
serde_json = "1.0"
tokio = { version = "0.2", features = ["macros", "tcp", "dns", "io-util"] }

[profile.release]
lto = true

[workspace]
members = [
	"core",
	"test_suite"
]
