[package]
name = "check_if_email_exists"
version = "0.1.1"
authors = ["Amaury Martiny <amaury.martiny@protonmail.com>"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "check_if_email_exists"
path = "src/bin/main.rs"
doc = false

[dependencies]
clap = {version = "2.32", features = ["yaml"]}
env_logger = "0.6"
lettre = "0.9"
log = "0.4"
native-tls = "^0.2"
rayon = "1.0.3"
trust-dns-resolver = "0.10.2"
