[package]
name = "check_if_email_exists"
version = "0.2.3"
authors = ["Amaury Martiny <amaury.martiny@protonmail.com>"]
edition = "2018"

[lib]
name = "check_if_email_exists"
path = "src/lib.rs"

[[bin]]
name = "check_if_email_exists"
path = "src/cli/main.rs"

[dependencies]
clap = { version = "2.32", features = ["yaml"] }
env_logger = "0.6"
lettre = { git = "https://github.com/lettre/lettre", rev = "1cbcbbb11f7a39a5d5d3829ce4162ca1beafedfb" }
log = "0.4"
native-tls = "^0.2"
rand = "0.6"
rayon = "1.0.3"
trust-dns-resolver = "0.10.2"

[workspace]
members = [
	"serverless"
]
