[package]
name = "check_if_email_exists"
version = "0.1.0"
authors = ["Amaury Martiny <amaury.martiny@protonmail.com>"]

[lib]
name = "check_if_email_exists"
path = "src/lib.rs"

[[bin]]
name = "check_if_email_exists_bin"
path = "src/bin/main.rs"

[dependencies]
clap = {version = "2.32", features = ["yaml"]}
env_logger = "0.5.13"
lettre = { git = "https://github.com/lettre/lettre" }
log = "0.4"
native-tls = "^0.2"
rayon = "1.0.3"
trust-dns-resolver = "0.10.2"
