# fly.toml app configuration file generated for backend2-fly on 2023-12-06T19:00:32+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "backend2-fly"
primary_region = "cdg"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 2048

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
