[package]
name = "check_if_email_exists"
version = "0.2.3"
authors = ["Amaury Martiny <amaury.martiny@protonmail.com>"]
default-run = "check_if_email_exists"
description = "Check if an email address exists without sending any email"
edition = "2018"
publish = false

[dependencies]
check_if_email_exists_core = { path = "../core" }
clap = { version = "2.32", features = ["yaml"] }
env_logger = "0.6"
futures = "0.1"
hyper = "0.12"
serde = "1.0"
serde_json = "1.0"
