[package]
name = "check_if_email_exists"
version = "0.2.0"
authors = ["Amaury Martiny <amaury.martiny@protonmail.com>"]
edition = "2018"

[dependencies]
check_if_email_exists_core = { path = "../check_if_email_exists" }
clap = { version = "2.32", features = ["yaml"] }
env_logger = "0.6"
lettre = { git = "https://github.com/lettre/lettre", rev = "1cbcbbb11f7a39a5d5d3829ce4162ca1beafedfb" }
