[package]
name = "check-if-email-exists"
version = "0.8.30"
authors = ["Amaury <amaurym10@protonmail.com>"]
categories = ["email"]
description = "Check if an email address exists without sending any email"
documentation = "http://docs.rs/check-if-email-exists"
edition = "2018"
keywords = ["email", "smtp", "mx", "verification"]
license = "AGPL-3.0"
publish = true
readme = "../README.md"
repository = "https://github.com/reacherhq/check-if-email-exists"

[badges]
appveyor = { repository = "reacherhq/check-if-email-exists", service = "github" }
travis-ci = { repository = "reacherhq/check-if-email-exists", service = "github" }

[dependencies]
async-native-tls = "0.3.3"
async-recursion = "1.0.0"
async-smtp = { version = "0.4.0", features = ["socks5"] }
async-std = "1.12.0"
async-std-resolver = "0.20.4"
fast-socks5 = "0.4.3"
futures = "0.3.21"
log = "0.4.17"
mailchecker = "4.1.17"
rand = {version = "0.8.5", features = ["small_rng"] }
regex = "1.5.6"
reqwest = { version = "0.11.11", features = ["json", "socks"] }
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.81"
trust-dns-proto = "0.20.4"

[dev-dependencies]
tokio = { version = "1.16.1" }
