[package]
name = "check-if-email-exists"
version = "0.8.19"
authors = ["Amaury Martiny <amaury.martiny@protonmail.com>"]
categories = ["email"]
description = "Check if an email address exists without sending any email"
documentation = "http://docs.rs/check-if-email-exists"
edition = "2018"
keywords = ["email", "smtp", "mx", "verification"]
license = "AGPL-3.0"
publish = true
readme = "../README.md"
repository = "https://github.com/reacherhq/check-if-email-exists"

[badges]
appveyor = { repository = "reacherhq/check-if-email-exists", service = "github" }
travis-ci = { repository = "reacherhq/check-if-email-exists", service = "github" }

[dependencies]
async-smtp = { git="https://github.com/amaurymartiny/async-smtp", branch="am-fast-socks", features = ["socks5"] }
async-std = "1.9.0"
async-std-resolver = "0.20.0"
fast-socks5 = "0.4.2"
futures = "0.3.12"
log = "0.4.14"
mailchecker = "4.0.3"
rand = {version = "0.8.3", features = ["small_rng"] }
regex = "1.4.3"
reqwest = { version = "0.11.0", features = ["json", "socks"] }
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.62"
trust-dns-proto = "0.20.0"

[dev-dependencies]
tokio = { version = "1.2.0" }
