[package]
name = "check-if-email-exists"
version = "0.9.1"
authors = ["Amaury <amaury@reacher.email>"]
categories = ["email"]
description = "Check if an email address exists without sending any email"
documentation = "http://docs.rs/check-if-email-exists"
edition = "2018"
keywords = ["email", "smtp", "mx", "verification"]
license = "AGPL-3.0"
publish = true
readme = "../README.md"
repository = "https://github.com/reacherhq/check-if-email-exists"

[dependencies]
async-native-tls = { version = "0.4", default-features = false }
async-recursion = "1.0.2"
async-smtp = { version = "0.6.0", features = ["socks5"] }
async-std = "1.12.0"
async-std-resolver = "0.21.2"
fantoccini = { version = "0.19.3", optional = true }
futures = { version = "0.3.26", optional = true }
fast-socks5 = "0.8.1"
log = "0.4.17"
mailchecker = "5.0.7"
rand = { version = "0.8.5", features = ["small_rng"] }
regex = "1.7.1"
reqwest = { version = "0.11.14", features = ["json", "socks"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
trust-dns-proto = "0.21.2"
md5 = "0.7.0"
levenshtein = "1.0.5"

[dev-dependencies]
tokio = { version = "1.25.0" }

[features]
headless = ["fantoccini", "futures"]
