[package]
name = "check_if_email_exists_core"
version = "0.2.3"
authors = ["Amaury Martiny <amaury.martiny@protonmail.com>"]
description = "Check if an email address exists without sending any email"
edition = "2018"
publish = false

[dependencies]
lettre = "0.9"
log = "0.4"
native-tls = "^0.2"
rand = "0.7"
rayon = "1.2.0"
trust-dns-resolver = "0.12.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
