[package]
name = "check-if-email-exists"
version = "0.8.14"
authors = ["Amaury Martiny <amaury.martiny@protonmail.com>"]
categories = ["email"]
description = "Check if an email address exists without sending any email"
documentation = "http://docs.rs/check-if-email-exists"
edition = "2018"
keywords = ["email", "smtp", "mx", "verification"]
license = "AGPL-3.0"
publish = true
readme = "../README.md"
repository = "https://github.com/amaurymartiny/check-if-email-exists"

[badges]
appveyor = { repository = "amaurymartiny/check-if-email-exists", service = "github" }
travis-ci = { repository = "amaurymartiny/check-if-email-exists", service = "github" }

[dependencies]
async-smtp = { version = "0.3", features = ["socks5"] }
async-std = "1.6"
async-std-resolver = "0.19"
fast-socks5 = "0.3"
futures = "0.3"
log = "0.4"
mailchecker = "3.3"
rand = "0.7"
regex = "1.4"
reqwest = { version = "0.10", features = ["json", "socks"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
trust-dns-proto = "0.19"

[dev-dependencies]
tokio = { version = "0.2", features = ["blocking"] }
