[package]
name = "check-if-email-exists"
version = "0.6.0"
authors = ["Amaury Martiny <amaury.martiny@protonmail.com>"]
categories = ["email"]
description = "Check if an email address exists without sending any email"
documentation = "http://docs.rs/check-if-email-exists"
edition = "2018"
keywords = ["email", "smtp", "mx", "verification"]
license = "GPL-3.0"
publish = true
readme = "../README.md"
repository = "https://github.com/amaurymartiny/check-if-email-exists"

[badges]
appveyor = { repository = "amaurymartiny/check-if-email-exists", service = "github" }
travis-ci = { repository = "amaurymartiny/check-if-email-exists", service = "github" }

[dependencies]
futures = "0.3"
lettre = "0.9"
log = "0.4"
mailchecker = "3.3"
native-tls = "^0.2"
rand = "0.7"
trust-dns-resolver = "0.12.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
