[package]
name = "check-if-email-exists-test-suite"
version = "0.8.24"
edition = "2018"
publish = false

[dependencies]
check-if-email-exists = { path = "../core" }
serde = "1.0.130"
serde_json = "1.0.68"
tokio = { version = "1.12.0", features = ["rt"] }
