[package]
name = "check-if-email-exists-test-suite"
version = "0.6.0"
edition = "2018"
publish = false

[dependencies]
check-if-email-exists = { path = "../core" }
futures = "0.3"
serde = "1.0"
serde_json = "1.0"
