[package]
name = "check-if-email-exists-test-suite"
version = "0.8.19"
edition = "2018"
publish = false

[dependencies]
check-if-email-exists = { path = "../core" }
serde = "1.0.123"
serde_json = "1.0.62"
tokio = { version = "1.2.0", features = ["rt"] }
