[package]
name = "check-if-email-exists-test-suite"
version = "0.7.1"
edition = "2018"
publish = false

[dependencies]
check-if-email-exists = { path = "../core" }
serde = "1.0"
serde_json = "1.0"
tokio = { version = "0.2", features = ["blocking"] }
